myFarm/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myHome.urls')),
    path('user/', include('users.urls'))
]

myHome/urls.py
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.index, name="home"),
    
    path("about/", views.about, name="AboutUs"),
    path("contact", views.contact, name="ContactUs"),
    path("blog", views.blog, name="Blog"),
    path("service", views.serve, name="Services"),
    path("sell_product", views.sell_product_view, name="sell_product"),
    path("sell", views.sell, name="Sell"),
    path("buy", views.buy, name="buy"),
    path("products_url", views.cart_products, name="products_url"),
    path("cart", views.cart, name="Cart"),
    path("crop/<int:pk>", views.single_crop, name="crop"),
    path("add_to_cart", views.add_to_cart, name="add_to_cart"),
    path("jobs", views.jobs, name="jobs"),
    path("user_to_us", views.user_to_us_view, name="user_to_us"),
    path("check_status", views.check_status, name="check_status"),
    path("worker_in_warehouse_url", views.worker_in_warehouse_view, name="worker_in_warehouse_url"),
    path("worker_in_distribution_url", views.worker_in_distribution_view, name="worker_in_distribution_url"),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register", views.register, name="register"),
    path('login',auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path("user_data", views.user_data, name="user_data"),
    path("farmer_crop_profile", views.farmer_crop_profile_view, name="farmer_crop_profile"),
    path("profile", views.profile, name="profile"),
]

myHome/models.py
from django.db import models
from users.models import Profile
from django.contrib.auth.models import User
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image,ImageDraw


    
class Sell_Product(models.Model):
    crop_owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    crop_name = models.CharField(max_length=200,null=True,blank=True)
    crop_quan = models.IntegerField(blank=True, null=True)
    crop_price = models.IntegerField(blank=True, null=True)
    crop_img = models.ImageField(null=True,blank=True,default="wheat.jpg")
    #selling_qr_code = models.ImageField(upload_to='selling_qr_image',blank=True)
    
    def __str__(self):
        return str(self.crop_name)
    
    # def save(self, *args, **kwargs):
    #     qr_data = f"Seller:- {self.crop_owner}"
        
    #     qrcode_img = qrcode.make(qr_data)
    #     canvas = Image.new('RGB', (500, 500), 'white')
    #     canvas.paste(qrcode_img)
    #     fname = f'selling_qr_code-{self.crop_name}.png'
    #     buffer = BytesIO()
    #     canvas.save(buffer,'PNG')
    #     self.qr_code.save(fname, File(buffer), save=False)
    #     canvas.close()
    #     super().save(*args, **kwargs)

class Cart(models.Model):
    current_user = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    cart_obj = models.ForeignKey(Sell_Product,null=True,blank=True,on_delete=models.SET_NULL)
    
    def __str__(self):
        return str(self.cart_obj)
 
class worker_in_warehouse(models.Model):
     user = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
     name = models.CharField(max_length=200,null=True,blank=True)
     phone = models.IntegerField(null=True,blank=True)
     email = models.EmailField(max_length=200,null=True,blank=True)
     location = models.CharField(max_length=200,null=True,blank=True)
     worker_img = models.ImageField(null=True,blank=True,upload_to="workers_img")

     def __str__(self):
        return str(self.name)
    
class worker_in_distribution(models.Model):
     user = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
     name = models.CharField(max_length=200,null=True,blank=True)
     phone = models.IntegerField(null=True,blank=True)
     email = models.EmailField(max_length=200,null=True,blank=True)
     location = models.CharField(max_length=200,null=True,blank=True)
     porter_img = models.ImageField(null=True,blank=True,upload_to="distributors_img")
     
     def __str__(self):
        return str(self.name)
    
    
# class Cart(models.Model):
#     cart_owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
#     cart_obj = models.CharField(max_length=200,null=True,blank=True)
    
#     def __str__(self):
#         return str(self.cart_owner)


class User_to_Farmeasy(models.Model):
    crop_owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.SET_NULL)
    crop_name = models.CharField(max_length=200,null=True,blank=True)
    crop_quantity = models.IntegerField(blank=True, null=True)
    crop_price = models.IntegerField(null=True,blank=True)
    crop_img = models.ImageField(null=True, blank=True)
    approved = models.BooleanField('Approved', default=False)

    def __str__(self):
        return str(self.crop_name)

myHome/forms.py
from django import forms 
from django.forms import ModelForm
from .models import Sell_Product,worker_in_warehouse,worker_in_distribution,User_to_Farmeasy

class CropForm(ModelForm):
    class Meta:
        model = Sell_Product
        #fields = '__all__'
        fields = ['crop_name','crop_quan','crop_price']
        
class WarehouseWorkerForm(ModelForm):
    class Meta:
        model = worker_in_warehouse
        #fields = '__all__'
        fields = ['name','phone','email','location','worker_img']

class DistributionWorkerForm(ModelForm):
    class Meta:
        model = worker_in_distribution
        #fields = '__all__'
        fields = ['name','phone','email','location','porter_img']
        

class UserToUsForm(ModelForm):
    class Meta:
        model = User_to_Farmeasy
        fields = ['crop_name','crop_quantity','crop_price','crop_img']
        
        
        

myHome/views.py
from django.shortcuts import render, redirect
from .models import Cart,Sell_Product,User_to_Farmeasy
from users.models import Profile
from .forms import CropForm,WarehouseWorkerForm,DistributionWorkerForm,UserToUsForm
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'myHome/index.html')

def cart_products(request):
    user_obj = Profile.objects.get(user=request.user)
    products = Cart.objects.filter(current_user=user_obj)
    total = 0
    for item in products:
        total += item.cart_obj.crop_price * item.cart_obj.crop_quan
    context = {'products':products,'total' :total}
    return  render(request,'myHome/cart.html',context)

@login_required(login_url="login")
def sell_product_view(request):

    crop_owner = Profile.objects.get(user=request.user)
    crop_name = request.POST.get("crop_name")
    crop_price = request.POST.get("crop_price")
    crop_quan = request.POST.get("crop_quan")
    crop_img = request.FILES.get("crop_img")
    
    # qr_img = request.FILES.get("crop_img")
    # list1 = []
    # for items in Sell_Product.objects.get(user=request.user):
    #     list1+=items
    
    if request.method == 'POST':
        # test`
        # test
        product_obj = Sell_Product.objects.get_or_create(crop_owner=crop_owner,crop_name=crop_name,crop_quan=crop_quan,crop_price=crop_price,crop_img=crop_img)
        return redirect('home')

    # form = CropForm()
    # if request.method == 'POST':
    #     form = CropForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('home')
    
    # context = {'form' : form}
    context = {}
    return render(request,"myHome/sell_form.html",context)

@login_required(login_url="login")
def buy(request):
    user_obj = Profile.objects.get(user=request.user)
    crops = Sell_Product.objects.all()
    #crops = Sell_Product.objects.filter(crop_owner=user_obj)
    context = {'crops':crops} 
    return  render(request,'myHome/Buy.html',context)


def single_crop(request, pk):
    #user_obj = Profile.objects.get(user=request.user)
    crop = Sell_Product.objects.get(id=pk)
    context = {'crop':crop} 
    return  render(request,'myHome/product.html',context)
    
def add_to_cart(request):
    crop_obj = request.POST.get('crop_obj')

    login_user = Profile.objects.get(user=request.user)
    buy_obj = Sell_Product.objects.get(id=crop_obj)
    obj = Cart.objects.create(current_user=login_user, cart_obj=buy_obj)

    # product_obj = Cart.objects.create()
    # product_obj.current_user = Profile.objects.get(user=request.user)
    # product_obj.cart_obj = Sell_Product.objects.get(id=crop_obj)
    # product_obj.save()
    return render(request,'myHome/index.html')


@login_required(login_url="login")
def jobs(request):
    return render(request,'myHome/jobs.html')

def worker_in_warehouse_view(request):
    form = WarehouseWorkerForm()
    if request.method == 'POST':
        form = WarehouseWorkerForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = Profile.objects.get(user=request.user)
            instance.save()
            return redirect('home')
    context = {'form' : form}
    return render(request,"myHome/worker_in_warehouse_form.html",context)

def worker_in_distribution_view(request):
    form = DistributionWorkerForm()
    login_user = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = DistributionWorkerForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = Profile.objects.get(user=request.user)
            #instance.worker_img = request.FILES.get(request.POST)
            instance.save()
            return redirect('home')
    context = {'form' : form}
    return render(request,"myHome/worker_in_distribution_form.html",context)

def user_to_us_view(request):
    form = UserToUsForm()
    if request.method == 'POST':
        form = UserToUsForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            #instance.crop_owner = request.user
            #login_user = Profile.objects.get(user=request.user)
            instance.crop_owner = Profile.objects.get(user=request.user)
            instance.save()
            #form.save()
            return redirect('home')
    
    context = {'form' : form}
    return render(request,"myHome/user_to_us_form.html",context)

def check_status(request):
    user_obj = Profile.objects.get(user=request.user)
    crops = User_to_Farmeasy.objects.filter(crop_owner=user_obj)
    context = {'crops':crops}
    return render(request, 'myHome/status.html',context)

def about(request):
    context = {}
    return render(request, 'myhome/about.html')

def contact(request):
   return render(request, 'myhome/contact.html')  

def blog(request):
    return render(request, 'myhome/blog.html')    

def serve(request):
   return render(request, 'myhome/services.html') 

def sell(request):
   return render(request, 'myhome/sell.html')        
    
def cart(request):
    return render(request, 'myhome/cart.html') 

   

myHome/templates/myHome/Buy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
</head>

<body>
    {% include 'myHome/navbar.html' %}
    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid mb-5">
        <div class="container text-center py-5">
            <h1 class="text-white display-3">Welcome to consumers page</h1>
            <div class="d-inline-flex align-items-center text-white">
                <p class="m-0"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-circle px-3"></i>
                <p class="m-0">Buy</p>
            </div>
        </div>
    </div>
    <!-- Header End -->

    {%block content %} 
        
        <div class="container-fluid pt-5">
            <div class="container">
                <div class="text-center pb-2">
                    <h6 class="text-primary text-uppercase font-weight-bold">Products</h6>
                    <h1 class="mb-4">Shop what you wanted</h1>
                </div>
                {% for obj in crops %}
                <div class="row pb-3">
                    <div class="col-lg-3 col-md-6 text-center mb-5">
                        <div class="d-flex align-items-center justify-content-center bg-primary mb-4 p-4">
                            <a href="{% url 'crop' obj.id %}">
                                <h6 class="text-white font-weight-medium m-0">{{obj.crop_name}}</h6>
                            </a>
                        </div>
                        <a href=""><p><img src="{{ obj.crop_img.url }}" alt=""></p></a>
                    </div>
                </div>
                {% endfor %}
            </div>
    {%endblock content %}
</div>

{% include 'myHome/footer.html' %}

</body>

</html>

myHome/templates/myHome/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>FASTER - Logistics Company Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body>
    {% include 'myHome/navbar.html' %}


    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid mb-5">
        <div class="container text-center py-5">
            <h1 class="text-white display-3">Contact</h1>
            <div class="d-inline-flex align-items-center text-white">
                <p class="m-0"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-circle px-3"></i>
                <p class="m-0">Contact</p>
            </div>
        </div>
    </div>
    <!-- Header End -->


    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 pb-4 pb-lg-0">
                    <div class="bg-primary text-dark text-center p-4">
                        <h4 class="m-0"><i class="fa fa-map-marker-alt text-white mr-2"></i>MIDC Road, Ambi , Pune</h4>
                    </div>
                    <iframe style="width: 100%; height: 470px;"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3777.853429059549!2d73.67718096469227!3d18.76008288726997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b23dba076905%3A0xf7debfcbc6df3b3d!2sAmbi%2C%20Maharashtra%20410507%2C%20India!5e0!3m2!1sen!2sbd!4v1670874397524!5m2!1sen!2sbd"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
                <div class="col-lg-7">
                    <h6 class="text-primary text-uppercase font-weight-bold">Contact Us</h6>
                    <h1 class="mb-4">Contact For Any Queries</h1>
                    <div class="contact-form bg-secondary" style="padding: 30px;">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="control-group">
                                <input type="text" class="form-control border-0 p-4" id="name" placeholder="Your Name"
                                    required="required" data-validation-required-message="Please enter your name" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="email" class="form-control border-0 p-4" id="email" placeholder="Your Email"
                                    required="required" data-validation-required-message="Please enter your email" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control border-0 p-4" id="subject" placeholder="Subject"
                                    required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control border-0 py-3 px-4" rows="3" id="message" placeholder="Message"
                                    required="required"
                                    data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary py-3 px-4" type="submit" id="sendMessageButton">Send
                                    Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    {% include 'myHome/footer.html' %}

</body>

</html>

myHome/templates/myHome/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<body>
    {% include 'myHome/navbar.html' %}

    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid mb-5">
        <div class="container text-center py-5">
            <h1 class="text-primary mb-4"></h1>
            <h1 class="text-white display-3 mb-5">FarmEasy</h1>
            <div class="mx-auto" style="width: 100%; max-width: 600px;">
                <div class="input-group">
                    <input type="text" class="form-control border-light" style="padding: 30px;" placeholder="Tracking Id">
                    <div class="input-group-append">
                        <button class="btn btn-primary px-3">Track & Trace</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->

    <!-- Features Start -->
    <div class="container-fluid bg-secondary my-5">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-5">
                    <img class="img-fluid w-100" src="{% static 'image/background.jpeg'%}" alt="">
                </div>
                <div class="col-lg-7 py-5 py-lg-0">
                    <h6 class="text-primary text-uppercase font-weight-bold">Why Choose Us</h6>
                    <h1 class="mb-4">"Fresh produce, simplified procurement - choose Farmeasy."</h1>
                    <p class="mb-4">Farmeasy is the ideal choice for businesses looking for high-quality farm produce. We work directly with farmers to ensure that our customers receive the freshest, most consistent products available. Our wide variety of products, competitive pricing, and convenient online ordering make it easy to meet your farm produce needs. Plus, with reliable delivery and personalized service, we'll work with you to ensure that your experience with us is seamless from start to finish. Choose Farmeasy and experience the best in farm produce supply.</p>
                    <ul class="list-inline">
                        <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>Best In Industry</h6>
                        <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>Emergency Services</h6></li>
                        <li><h6><i class="far fa-dot-circle text-primary mr-3"></i>24/7 Customer Support</h6></li>
                    </ul>
                    <a href="" class="btn btn-primary mt-3 py-2 px-4">Learn More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Features End -->

    {% include 'myHome/footer.html' %}

</body>

</html>

myHome/templates/myHome/jobs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title></title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'style.css' %}" rel="stylesheet">
</head>

<body>
    {% include 'myHome/navbar.html' %}


    <!-- Header Start -->
    <div class="jumbotron jumbotron-fluid mb-5">
        <div class="container text-center py-5">
            <h1 class="text-white display-3">Our Jobs</h1>
            <div class="d-inline-flex align-items-center text-white">
                <p class="m-0"><a class="text-white" href="">Home</a></p>
                <i class="fa fa-circle px-3"></i>
                <p class="m-0">jobs</p>
            </div>
        </div>
    </div>
    <!-- Header End -->

     <!-- Services Start -->
     <div class="container-fluid pt-5">
        <div class="container">
            <div class="text-center pb-2">
                <h6 class="text-primary text-uppercase font-weight-bold">Our Jobs</h6>
                <h1 class="mb-4">"JOIN FARMEASY TO BRING THE CHANGE"</h1>
            </div>
            <div class="row pb-3">
                <div class="col-lg-3 col-md-6 text-center mb-5">
                    <div class="d-flex align-items-center justify-content-center bg-primary mb-4 p-4">
                        <a href="{% url 'worker_in_distribution_url' %}"><h6 class="text-white font-weight-medium m-0">Join as a distribution partner</h6></a>
                    </div>
                    <p>Join FarmEasy to organize the distribution supply chain.</p>
                </div>
                <div class="col-lg-3 col-md-6 text-center mb-5">
                    <div class="d-flex align-items-center justify-content-center bg-primary mb-4 p-4">
                        <a href="{% url 'worker_in_warehouse_url' %}"><h6 class="text-white font-weight-medium m-0">Join as a warehouse worker</h6></a>
                    </div>
                    <p>Join FarmEasy to maintain the Crops quality in the warehouse storage.</p>
                </div>
                <div class="col-lg-3 col-md-6 text-center mb-5">
                    <div class="d-flex align-items-center justify-content-center bg-primary mb-4 p-4">
                       <a href="#"> <h6 class="text-white font-weight-medium m-0">Join in a farmer community</h6></a>
                    </div>
                    <p>Join the India's biggest farmer community to spread awareness about the Agriculture market.</p>
                </div>
                <div class="col-lg-3 col-md-6 text-center mb-5">
                    <div class="d-flex align-items-center justify-content-center bg-primary mb-4 p-4">
                        <a href="#"><h6 class="text-white font-weight-medium m-0">Coming Soon...</h6></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Services End -->




    {% include 'myHome/footer.html' %}

</body>

</html>

myHome/templates/myHome/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.max.css' %}">
</head>
<body>
    
    <form action="/signup" method="post">
        {% csrf_token %}
    <div class="container">
            <div class="login-container">
                <input id="item-1" type="radio" name="item" class="sign-in" checked><label for="item-1" class="item">Sign In</label>
                <input id="item-2" type="radio" name="item" class="sign-up"><label for="item-2" class="item">Sign Up</label>
                <div class="login-form">
                    <div class="sign-in-htm">
                        <div class="group">
                            <input placeholder="Username" id="user" name = "user_name" type="text" class="input">
                        </div>
                        <div class="group">
                            <input placeholder="Password" id="pass" name = "password" type="password" class="input" data-type="password">
                        </div>
    
                        <div class="group">
                            <a href=""><input type="submit" class="button" value="Sign In"></a>
                        </div>
                        <div class="hr"></div>
                        <div class="footer">
                            <a href="#forgot">Forgot Password?</a>
                        </div>
                    </div>
                </form>
                    <form action="signup" method="post">
                        {% csrf_token %}
                    <div class="sign-up-htm">
                        <div class="group">
                            <input placeholder="Username" id="user" name= "user_name" type="text" class="input">
                        </div>
    
                        <div class="group">
                            <input placeholder="Email adress" id="pass" name = "email_address" type="text" class="input">
                        </div>
                        <div class="group">
                            <input placeholder="mobile number" id="pass" name = "mobile_number" type="number" class="input" data-type="number">
                        </div>
                        <div class="group">
                            <input placeholder="pincode" id="pass" name = "pincode"type="number" class="input" data-type="pincode">
                        </div>
                        <div class="group">
                            <input placeholder="state" id="pass" name = "state" type="text" class="input" data-type="state">
                        </div>
                
                        <div class="group">
                            <input placeholder="Password" id="pass" name = "password" type="password" class="input" data-type="password">
                        </div>
                        <div class="group">
                            <input placeholder="Repeat password" id="pass" name = "repeat_password" type="password" class="input" data-type="password">
                        </div>
    
                        <div class="group">
                            <input type="submit" class="button" value="Sign Up">
                        </div>
                        <div class="hr"></div>
                        <div class="footer">
                            <label for="item-1">Already have an account?</a>
                    </div>
                </form> 
                </div>
            </div>
        </div>
</body>
</html>

myHome/templates/myHome/sell_form.html
{% include 'myHome/navbar.html' %}

{% block content %}


    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <br>
                <hr>


                <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <center>
                    <p>
                        <label for="id_crop_name">Crop Name:</label>
                        <input type="text" name="crop_name" maxlength="200" id="id_crop_name" value="">
                    </p>
                    <p>
                        <label for="id_crop_quan">Crop Quantity:</label>
                        <input type="number" name="crop_quan" id="id_crop_quan" value="">
                    </p>
                    <p>
                        <label for="id_crop_price">Crop price:</label>
                        <input type="number" name="crop_price" id="id_crop_price" value="">
                    </p>
                    <p>
                        <label for="id_crop_price">Upload Crop Image: </label>
                        <input type="file" id="avatar" name="crop_img" accept="image/png, image/jpeg">
                    </p>


                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit">
                    </center>
                </form>
            </div>
        </div>
    </main>

{% endblock content %}
{% include 'myHome/footer.html' %}

myHome/templates/myHome/status.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cart</title>
    <link rel="stylesheet" href="{% static 'product.css' %}">
</head>
<body>
  {% include 'myHome/navbar.html' %}

    {%block content %}
        {% for obj in crops%}
            <h1> Hello : {{ obj.crop_owner.name }}</h1>
            <h1> Crop Selling : {{obj.crop_name}}</h1>
            <h1> Crop Quantity : {{ obj.crop_quantity }}</h1>
            <h1> Crop Price/Kg : {{obj.crop_price }}</h1>
            <h1> Request to sell/Approved Request : {{obj.approved }}</h1>
            <h1>------------------------------------------------------------</h1>
        {% endfor %}
    {%endblock content %}
</body>
</html>

myHome/templates/myHome/user_to_us_form.html
{% include 'myHome/navbar.html' %}

{% block content %}

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <br>
                <center> <form class="form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                   {{ form.as_p }}
                    {% comment %} {{ form.as_p }} {% endcomment %}
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit/Apply" /><br>
                    <a href="{% url 'check_status' %}">Check Status</a>
                </form> </center>
            
            </div>
        </div>
    </main>

{% endblock content %}
{% include 'myHome/footer.html' %}